### ISSUE TITLE
Possible to consolidate / streamline the various agreements and attestations?

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#14]
![image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/5fc825d0-bfcf-4fa4-9a68-3600c8cb6254)

also, we might consider making them a sequence of modals/ lightboxes that pop up after user clicks [ Submit ] on a validated form. 

@ss12430 should weigh in.

**Comment by ss12430** [comment]
Yes! We are covering many of these attestations in our safety training. So these can be edited down to the following:

"I will reset any furniture that I moved, clean up after myself, and not leave anything behind."
"If I need to cancel my reservation, I will email the Media Commons." 

I agree that these can be a sequence of lightboxes

**Comment by nopivnick** [comment]
I think we can get rid of the third agreement block as both these attestations are already covered either in the modal when the booking page first loads or in the agreement statement above.


![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/4398a734-0551-4e53-8338-f46f2499d35c)
