### ISSUE TITLE
As Samantha I want new approval emails (all of which are sent from my account) to be visible in my Gmail inbox.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#145]

**Comment by lucia-gomez** [comment]
cc her?

**Comment by nopivnick** [comment]
sure. cc her.

**Comment by lucia-gomez** [comment]
Samantha is cc'd on approval emails sent from prod or staging. On development branches we cc media-commons-devs instead


![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/b42bc411-8a20-4014-bfd8-559c8c607344)



![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/baf551d1-f1ed-4be7-9cab-1c1c108fd364)
