### ISSUE TITLE
As an end-user I want to Reply to any status update notification email and have the reply sent To: <mediacommons.reservations@nyu.edu>

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#146]

**Comment by lucia-gomez** [comment]
seems to already be implemented 

![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/3678ae41-9c8f-4546-9531-d530d9a5ef85)

**Comment by lucia-gomez** [comment]
Seems like Riho already took care of this!
