### ISSUE TITLE
As an end-user I want the Subj: heading of all request status email notifications to have the formula "{STATUS}: Media Commons request for "{Title}""

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#151]
Statuses:

REQUESTED
DENIED
PRE-APPROVED
APPROVED
CANCELED
CHECKED-IN
NO SHOW

**Comment by lucia-gomez** [comment]
![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/f885334c-d852-49e5-ae0d-98a312238cd4)
