### ISSUE TITLE
Upon selecting Room 221 or 222, a modal / lightbox should open w/ a message regarding mocap equipment

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#16]
possible modal language (@ss12430 may want to weigh-in):

> PLEASE NOTE: If you intend to use the motion capture rig in Room 221 you'll also need to book Room 222 concurrently.

![image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/d272bc8e-534c-4008-bb30-25bc7bff05d1)

**Comment by ss12430** [comment]
@nopivnick can you say a little more about what you mean? Language looks good to me. 

One note @rlho - room 220 is now named "220 Black Box" instead of "220 Conference Room"

**Comment by nopivnick** [comment]
@rlho I think the modal should only pop up once when changing the checkbox status for Room 221. currently, it pops up every time you select an additional room.

to replicate:

1. select Room 221 (modal pops up)
2. click on modal button to dismiss
3. select Room 222 (modal pops up)
4. click on modal button to dismiss
5. select Room 223 (modal pops up)
6. click on modal button to dismiss
7. etc., etc.

expected behavior:

1. select Room 221 (modal pops up)
2. click on modal button to dismiss
3. select Room 222 (no modal)
4. select Room 223 (no modal)

**Comment by nopivnick** [comment]
we should trigger the modal upon selecting room 222 as well.

new modal language:

> PLEASE NOTE: If you intend to use the motion capture rig in Room 221 or Room 222, you'll need to book both rooms concurrently.
