### ISSUE TITLE
As Jhanele I want the event title formula to be {STATUS} {Room #s} {Dept.} {Title of reservation}.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#196]

**Comment by nopivnick** [comment]
@lucia-gomez any guess when this might be ready for `Prod`?

**Comment by lucia-gomez** [comment]
Planning to finish this tonight

**Comment by lucia-gomez** [comment]
![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/1afc1115-80c3-48aa-a896-88083d9cce51)
![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/b4577313-4e2e-4c84-a835-fdbe4499678c)
