### ISSUE TITLE
As Jhanele I want specific booking details to appear in the calendar event description so that PAs know what is expected of them.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#198]
Fields that should appear in the event description:

**Reservation Details**

- Reservation Title:
- Reservation Description:
- Expected Attendance:
- Room setup needed?:
- Media Services:
- Catering:
- Catering Details:
- Hire Security:

**Cancelation Policy**

- (policy language)

**Comment by nopivnick** [comment]
@lucia-gomez @rlho can either of you take this on sooner rather than later?

**Comment by lucia-gomez** [comment]
Can do this tonight unless Riho gets to it first

**Comment by lucia-gomez** [comment]
![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/c77aed40-8ae8-448f-b4f0-81f3cbb2f72b)
![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/05204418-8b4b-4f16-a6e5-49fdcd995b87)

**Comment by nopivnick** [comment]
@lucia-gomez that's some fine looking event description right there.

one suggestion: I'd format Cancelation Policy as a heading in bold, same as Requestor and Reservation Details, followed by the policy text below. and one edit to the second sentence: "Failure to cancel an unused booking is considered a no-show and may result in restricted use of the space."

**Comment by nopivnick** [comment]
@lucia-gomez Samantha and Jhanele have asked that we strike the Requestor Details from the Description field, only the Reservation Details and Cancelation Policy should be present.

**Comment by lucia-gomez** [comment]
Updated event description content based on above comments 

![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/c30ce074-5cce-4836-839e-3ae91d29bdfd)
