### ISSUE TITLE
As a PA I want to be able to sort bookings on the Bookings tab of the PA page by Start Date, End Date and NetID.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#204]

**Comment by lucia-gomez** [comment]
Hang on, @Kaibanda can you hold off on this? Any changes you might make here will conflict with a larger UI refactor I have in progress

**Comment by lucia-gomez** [comment]
This is ready to implement **on the refactorUi branch** now, where the new MUI table is implemented

**Comment by nopivnick** [comment]
this will be addressed in the new UI.
