### ISSUE TITLE
Update Catering Information section on new form

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#41]
We do not collect chartfields anymore.

> It is required for the reservation holder to pay and arrange for CBS cleaning services if the event includes catering. [Please see this link for more information](https://nyu.service-now.com/csmp?id=sc_cat_item&sys_id=c78a46241bb234901416ea02b24bcb26&referrer=popular_itemshttps://nyu.service-now.com/csmp?id=sc_cat_item&sys_id=c78a46241bb234901416ea02b24bcb26&referrer=popular_items).

![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/7c1474ab-768c-437f-98d3-d57cbced0315)

**Comment by nopivnick** [comment]
@ss12430 the link on the current Reservation Request Form (see above) doesn't appear to work (blank page). can you post the 'for more information' link you want here?

**Comment by ss12430** [comment]
I see! It looks like service link took that page offline. I removed the link altogether

**Comment by nopivnick** [comment]
@rlho I still see the "Please see this link for more information" link, did you update the Apps Script version on the Production Deployment?


![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/c7212f1f-119b-4f54-859c-a667cdbe3f6c)
