### ISSUE TITLE
Admin page doesn't render correctly after adding or removing a user from the Safety Training, Ban, Admin users, and Liaisons tabs.

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#45]
to replicate:

1. visit the [Admin page](https://sites.google.com/nyu.edu/370j-booking/admin)
2. click on the Safety Training, Ban, Admin users or Liaisons tab
3. enter an email
4. click the [Add] button

OR

1. visit the [Admin page](https://sites.google.com/nyu.edu/370j-booking/admin)
2. click on the Safety Training, Ban, Admin users or Liaisons tab
3. click the [Remove] button

**Comment by rlho** [comment]
https://github.com/ITPNYU/mc-reservation-tool/pull/51

**Comment by nopivnick** [comment]
newly added email addresses don't appear on the page when clicking [ Add User ] button on Safety Training and Ban tabs under the Admin page

**Comment by nopivnick** [comment]
@rlho Admin page > Liaisons tab appears to process adding user and gets stuck if Dept. dropdown isn't selected.


![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/69ffbc19-d675-4780-86ab-3577bcd97200)


![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/30855db9-1b84-42ba-bb11-8bb70e3b7455)


![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/22a58aee-d5d5-4970-ab6c-2b8e5eb27ee2)

to replicate:

1. click on Admin page
2. click on Liaisons tab
3. enter email address
4. click Add User button
5. browser alert appears
6. click okay
7. wait indefinitely

expected behavior:

1. click on Admin page
2. click on Liaisons tab
3. enter email address
4. click Add User button
5. browser alert appears
6. click okay
7. return to pre-Add User button click state
