### ISSUE TITLE
BUG: Adding a user who is already listed in the Safety training; Ban; PA users; Admin users; and Liaisons tabs causes app to hang

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#71]
![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/9cf8d53a-50be-44aa-bc44-e624575a28d0)

![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/382340fe-a34e-49cb-8e64-ef8970081b26)

**Comment by lucia-gomez** [comment]
This hasn't been an issue for a while


![Image](https://github.com/ITPNYU/mc-reservation-tool/assets/51058748/71d98ada-caa7-4f3c-9ffb-c9c724326279)
