### ISSUE TITLE
Adjusted block of time after initial selection isn't reflected in multiple rooms

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#8]
![image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/e16fa642-c433-4ca7-8365-231edb3b0e96)

to replicate:

1. select two or more rooms
2. select a block of time
3. click on the bottom of the event and change the end time

expected behavior:

changes to the event's start or end time should be mirrored across multiple rooms if present.

**Comment by rlho** [comment]
https://github.com/ITPNYU/mc-reservation-tool/pull/54
