### ISSUE TITLE
Dark Mode in macOS System Settings makes reservation request form illegible

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#9]
<img width="827" alt="Screenshot 2023-08-31 at 11 25 40 AM" src="https://github.com/ITPNYU/mc-reservation-tool/assets/688639/b0235c38-368b-4dee-865e-6643fc1d3c24">

![image](https://github.com/ITPNYU/mc-reservation-tool/assets/688639/d70bf530-96ad-4cb6-8b42-eb7915a0bc0d)

**Comment by rlho** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
