### ISSUE TITLE
As a Product Manager, I want links to the Admin and PA pages to be inside the web app so I don't have to kludge a solution using separate pages in Goggle Sites

### ISSUE THREAD

**Issue by nopivnick** [ITPNYU/mc-reservation-tool#98]

**Comment by lucia-gomez** [comment]
Should these links only be visible to users who have access to those pages? Ex a normal student can't see a link to the Admin or PA pages?

**Comment by nopivnick** [comment]
@lucia-gomez

> Should these links only be visible to users who have access to those pages? Ex a normal student can't see a link to the Admin or PA pages?

yes!

furthermore, a PA doesn't need to see the Admin link.

I wonder whether we might need better UI nomenclature?

@Greenfishyy may have some ideas about how we break down the different screens and which screens should be the default for a given user type. e.g., maybe we should split what we're currently calling the Admin page into a Bookings page while the other tabs belong in a Settings page? and maybe for an Admin-type and a PA-type user the UI defaults to the Bookings page?
